import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import { Container, Row } from 'react-bootstrap'

export default function Home() {
  const router = useRouter()
  return (
    <Container className="d-flex flex-column justify-content-center ">
      <Head>
        <title>Quizelny — онлайн викторины</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row className=" mb-4">
        <h1 className="text-center">
          Quizelny — это сайт, где вы можете проходить разные викторины.  
        </h1>
      </Row>
      <Row className="mb-4">
        <h2 className="text-center">
        Вы можете создавать свою викторину в удобном конструкторе, а также делиться ею с друзьями
        </h2>
      </Row>
      <Row className="mb-4">
        <h2 className="text-center">
        На данный момент доступны виды квизов: 
        <span 
          className="link"
          onClick={()=>router.push(process.env.SOUND_URL)}
        >
          {' '}АудиоКвиз
        </span> 
        </h2>
      </Row>

      <Row>
        <h2 className="text-center">
          Приятного времяпрепровождения!
        </h2>
      </Row>
     
    </Container>
    
  )
}
